
import java.awt.Color;
import java.awt.Font;
import static java.awt.font.TextAttribute.FONT;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JColorChooser;
import javax.swing.JFileChooser;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Semih Durbal
 */
public class NotepadUygulamasi extends javax.swing.JFrame {

    /**
     * Creates new form NotepadUygulamasi
     */
    public NotepadUygulamasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        yazi_alani = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        openFolder = new javax.swing.JMenuItem();
        saveFolder = new javax.swing.JMenuItem();
        quitFolder = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        changeColor = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        arielType = new javax.swing.JMenuItem();
        changeFont = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        yazi_alani.setColumns(20);
        yazi_alani.setRows(5);
        jScrollPane1.setViewportView(yazi_alani);

        jMenu1.setText("Dosya");

        openFolder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        openFolder.setText("Dosya Aç");
        openFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFolderActionPerformed(evt);
            }
        });
        jMenu1.add(openFolder);

        saveFolder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        saveFolder.setText("Dosya Kaydet");
        saveFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFolderActionPerformed(evt);
            }
        });
        jMenu1.add(saveFolder);

        quitFolder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        quitFolder.setText("Dosya Kapat");
        quitFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitFolderActionPerformed(evt);
            }
        });
        jMenu1.add(quitFolder);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Düzenle");

        jMenu3.setText("Renk");

        changeColor.setText("Rengi Değiştir");
        changeColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeColorActionPerformed(evt);
            }
        });
        jMenu3.add(changeColor);

        jMenu2.add(jMenu3);

        jMenu4.setText("Yazı Tipi");

        arielType.setText("Ariel");
        arielType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arielTypeActionPerformed(evt);
            }
        });
        jMenu4.add(arielType);

        changeFont.setText("Times New Roman");
        changeFont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeFontActionPerformed(evt);
            }
        });
        jMenu4.add(changeFont);

        jMenu2.add(jMenu4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFolderActionPerformed
        // TODO add your handling code here:
        
        JFileChooser fc = new JFileChooser();
        int i = fc.showOpenDialog(this);
        
        if(i==JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            String icerik = "";
            
            try(Scanner scanner = new Scanner(new BufferedReader(new FileReader(file)))){
                
                while(scanner.hasNextLine()){
                    icerik += scanner.nextLine() + "\n";
                }
                yazi_alani.setText(icerik);
                
            } catch (FileNotFoundException ex) {
                yazi_alani.setText("Dosya Bulunamadı");
            }
            
        }
        
    }//GEN-LAST:event_openFolderActionPerformed

    private void changeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeColorActionPerformed
        // TODO add your handling code here:
        Color color = JColorChooser.showDialog(this, "Bir renk seçiniz", Color.green);
        yazi_alani.setForeground(color);
        
    }//GEN-LAST:event_changeColorActionPerformed

    private void quitFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitFolderActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_quitFolderActionPerformed

    private void arielTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arielTypeActionPerformed
        // TODO add your handling code here:
        Font font = new Font("Arial" ,FONT.KERNING_ON,20);
        yazi_alani.setFont(font);
    }//GEN-LAST:event_arielTypeActionPerformed

    private void saveFolderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFolderActionPerformed
        // TODO add your handling code here:
        JFileChooser sf = new JFileChooser();
        int cevap = sf.showSaveDialog(this);
        if(cevap == JFileChooser.APPROVE_OPTION){
            
            String dosya_yolu = sf.getSelectedFile().getPath();
            try(FileWriter writer = new FileWriter(dosya_yolu)){
                
                writer.write(yazi_alani.getText());
                
            } catch (IOException ex) {
                Logger.getLogger(NotepadUygulamasi.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
    }//GEN-LAST:event_saveFolderActionPerformed

    private void changeFontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeFontActionPerformed
        // TODO add your handling code here:
        Font font = new Font("Times New Roman" ,FONT.LIGATURES_ON,11);
        yazi_alani.setFont(font);
    }//GEN-LAST:event_changeFontActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotepadUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotepadUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotepadUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotepadUygulamasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotepadUygulamasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem arielType;
    private javax.swing.JMenuItem changeColor;
    private javax.swing.JMenuItem changeFont;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem openFolder;
    private javax.swing.JMenuItem quitFolder;
    private javax.swing.JMenuItem saveFolder;
    private javax.swing.JTextArea yazi_alani;
    // End of variables declaration//GEN-END:variables
}
